### ISSUE TITLE
SDK 2.x - alphaでサーバーに接続できません

### ISSUE THREAD

**Issue by yasuhirom** [Project-PLATEAU/PLATEAU-SDK-for-Unity#1]
SDK 2.x -alphaでサーバーにアクセスができません。
インポート元をサーバーに設定すると「サーバーへの問い合わせに失敗しました」とエラーが出ます。
<img width="622" alt="ScreenCapture 2023-11-04 19 10 27" src="https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unity/assets/101092007/8f559df1-0c25-484b-a73e-39376f50d191">
インポート元をローカルに設定すると範囲選択を行おうとすると「メッシュコードの取得に失敗しました」と出ます。
<img width="490" alt="ScreenCapture 2023-11-04 19 08 41" src="https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unity/assets/101092007/ea9034bf-ae1b-48d8-b6e9-71921cfb1422">

SDK v1.1.6.1ではインポート元をサーバー/ローカルのどちらでもデータのインポートが可能です。

環境は
MacBook Pro (2018), macOS X 10.15.7
Unity : 2021.3.30f1と2023.1.16f1とで試しまたがどちらも同じ症状です。
インターネットはもちろん接続されています。

よろしくお願いします。

三井

**Comment by tomoki-suzuki-syn** [comment]
以前は、MacOSについてはArmアーキテクチャのCPUのみ対応しており、MacBook Pro(2018)などIntel CPUのMacには対応しておらず、大変お手数をおかけしました。
現在はIntel CPUのMacにも対応しており、お使いのMacBook Pro(2018)でも動作するようになりました。
