### ISSUE TITLE
インポートしたデータがずれます。

### ISSUE THREAD

**Issue by yasuhirom** [Project-PLATEAU/PLATEAU-SDK-for-Unity#2]
データをインポートすると道路と建物、テクスチャーの付いた建物と付いていない建物が上下にずれた状態になるのですが、元のデータがこの状態なのでしょうか？
それとも私の環境のせいでしょうか？

環境は
MacBook Pro 15inch(2018), macOS X 10.15.7
PLATEAU SDK ver 1.6.1
Unity 2021.3.30f1、2023.1.16fのどちらでも。
インポートを試した地図データは、
- GISのWebからダウンロードした神奈川県相模原市のデータ、東京都竹芝のデータ
- SDKでサーバーから直接ダウンロードした静岡県熱海市、東伊豆市のデータ
のどれでも起こっています。

竹芝のデータと相模原市のデータでの画面のキャプチャを下記に添付します。
相模原
少し上から見るとちゃんとしてそうなのですが
<img width="1318" alt="ScreenCapture 2023-11-04 22 15 11" src="https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unity/assets/101092007/1d61e7b2-d76d-461c-a6cc-0270e2005677">
Z軸を降りていくと道路？がずれている雰囲気です。
<img width="1318" alt="ScreenCapture 2023-11-04 22 15 24" src="https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unity/assets/101092007/07621d2d-5d2a-4c35-8e0e-600cb6c533ae">

竹芝も同様にZ軸を降りていくと近都市のようにテクスチャーのついたものが下にあります。
<img width="1453" alt="ScreenCapture 2023-11-04 16 01 31" src="https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unity/assets/101092007/a3eb6595-85d4-437d-9acd-eed01c9539b7">

よろしくお願いします。

三井

**Comment by tomoki-suzuki-syn** [comment]
### 道路が下に埋まっていることについて：
LOD1の道路には高さ情報がないため、高さ0としてインポートされます。
道路に高さ情報があるのは、LOD2以上となります。
道路の高さを地形と合わせる機能については、今後の開発課題とさせて頂きます。

### 竹芝でテクスチャの付いた建物が下に埋まっていることについて：
調査しましたが、すみません、手元のマシンでは再現しませんでした。
SDKの最新版をご利用いただき、それでも解決しない場合は、お手数ですが次の情報をご教示頂ければと思います：

- SDKのバージョン(v1.6.1は存在しません)
- OS
- どのデータセットを利用したか
- インポートした範囲の番号（範囲選択画面で青い数値で表示される番号）

**Comment by yasuhirom** [comment]
ありがとうございます。
新しいもの(PLATEAU-SDK-for-Unity-v2.3.0.tgz/Unity 2021.3.30f1 Personal)で試したところ問題なく表示されました。

<img width="759" alt="ScreenCapture 2024-01-21 17 42 12" src="https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unity/assets/101092007/ee40e3f7-c25e-41de-ae0f-18b7c07f0cb8">

ありがとうございました。
