### ISSUE TITLE
OBJファイルが正しくエクスポートされない

### ISSUE THREAD

**Issue by yatou-chika** [Project-PLATEAU/PLATEAU-SDK-for-Unity#3]
OBJを出力時、座標軸はENU、WUN、ESU、EUNの４つを選択できますが、
どれを選んでも全て同じOBJファイルが出力されます。
また、出力されたファイルは建物高さ向きが上下逆になっています。
Unityエディターバージョン：2022.3.12F1
PLATEAU SDK for Unity v2.1.1-alpha
[桐生市民文化会館.pptx](https://github.com/Project-PLATEAU/PLATEAU-SDK-for-Unity/files/13386712/default.pptx)

**Comment by tomoki-suzuki-syn** [comment]
座標軸が正しくない問題について、お手数をおかけして申し訳ございません。
v2.3.0で修正いたしました。
