### ISSUE TITLE
iOSのPrivacy Manifestへの対応について

### ISSUE THREAD

**Issue by tommy-tommy** [Project-PLATEAU/PLATEAU-SDK-for-Unity#7]
---

**★使用環境**

Unity：2022.3.37f1
SDK：v2.3.2
ターゲットプラットフォーム：Android、iOS

---

現在、上記環境でスマホアプリゲームを作成しています
今回iOSアプリについて、アプリを一通り作成してAppleに審査を出したところ、

> Your app includes “Frameworks/plateau.framework/plateau”, which includes BoringSSL / openssl_grpc, an SDK that was identified in the documentation as a privacy-impacting third-party SDK

という返答が来ました

5/1以降、iOSアプリを作成する際はPrivacyManifestというものに対応させる必要があることになっているのですが、
本バージョンのSDKでは未対応となっているようです
https://developer.apple.com/jp/news/?id=3d8a9yyh

そこで一点質問なのですが、SDKバージョン3.x系はPrivacyManifestに対応していますでしょうか？
している場合はバージョンアップデートしようと思っていますが、
対応していない場合、対応をお願いしたいと考えています
よろしくお願いいたします

**Comment by SYN-miyamoto** [comment]
PLATEAU SDK のご利用ありがとうございます。
現状PLATEAU SDKは、Privacy Manifestに対応していませんが、2025年春までに対応予定です。
SDKをランタイムから使っていない場合は、SDKを削除してビルドする形で対応をお願いします。

**Comment by tommy-tommy** [comment]
ご返答ありがとうございます
2025年春に対応とのこと承知しました

また、対応手段のご提示もありがとうございます
確かに今回のアプリはランタイムでは使用していないものになりますので、
一旦ビルド時にSDKを削除する、という手段で対応してみます

issue自体は解決しましたのでクローズとさせていただきます
